export const STORE_USER_INFO = 'STORE_USER_INFO';
export const SET_SUCCESSFUL_ACCOUNT_CREATION ='SET_SUCCESSFUL_ACCOUNT_CREATION';
export const SAVE_DUOLINGO_USERNAME_STATE = 'SAVE_DUOLINGO_USERNAME_STATE';
export const SET_USER_VERIFIED = 'SET_USER_VERIFIED';
export const SAVE_TEMP_DUO_ID = 'SAVE_TEMP_DUO_ID';
export const SET_VERIFICATION_RESULT = 'SET_VERIFICATION_RESULT';
